export default [
  {
    id: '100',
    artistName: 'Miguel Ft. Travis Scott',
    name: 'Skywalker',
    likeCount: '50k',
    media: 'https://s3-us-west-2.amazonaws.com/zach-random-stuff/skywalker.mp4',
  },
  {
    id: '101',
    artistName: 'Taylor Swift',
    name: 'Look What You Made Me Do',
    likeCount: '100k',
    media: 'https://s3-us-west-2.amazonaws.com/zach-random-stuff/look.mp4',
  },
  {
    id: '1',
    artistName: 'Miguel Ft. Travis Scott',
    name: 'Skywalker',
    likeCount: '50k',
    media: 'https://www.appsloveworld.com/wp-content/uploads/2018/10/640.mp4',
  },
  {
    id: '2',
    artistName: 'Taylor Swift',
    name: 'Look What You Made Me Do',
    likeCount: '100k',
    media: 'https://www.appsloveworld.com/wp-content/uploads/2018/10/Sample-Videos-Mp425.mp4',
  },
  {
    id: '3',
    artistName: 'Khalid',
    name: 'Young Dumb & Broke',
    likeCount: '2k',
    media: 'https://s3-us-west-2.amazonaws.com/zach-random-stuff/young.mp4',
  },
  {
    id: '4',
    artistName: 'Khalid',
    name: 'Young Dumb & Broke',
    likeCount: '2k',
    media: 'http://techslides.com/demos/sample-videos/small.webm',
  },
  {
    id: '5',
    artistName: 'Khalid',
    name: 'Young Dumb & Broke',
    likeCount: '2k',
    type: 'm3u8',
    media: 'https://multiplatform-f.akamaihd.net/i/multi/will/bunny/big_buck_bunny_,640x360_400,640x360_700,640x360_1000,950x540_1500,.f4v.csmil/master.m3u8',
  },
  {
    id: '6',
    artistName: 'Khalid',
    name: 'Young Dumb & Broke',
    likeCount: '2k',
    type: 'm3u8',
    media: 'http://amssamples.streaming.mediaservices.windows.net/91492735-c523-432b-ba01-faba6c2206a2/AzureMediaServicesPromo.ism/manifest(format=m3u8-aapl)',
  },
  {
    id: '7',
    artistName: 'Khalid',
    name: 'Young Dumb & Broke',
    likeCount: '2k',
    type: 'm3u8',
    media: 'https://multiplatform-f.akamaihd.net/i/multi/april11/sintel/sintel-hd_,512x288_450_b,640x360_700_b,768x432_1000_b,1024x576_1400_m,.mp4.csmil/master.m3u8',
  },
  {
    id: '9',
    artistName: 'Khalid',
    name: 'FPT',
    likeCount: '2k',
    type: 'm3u8',
    media: 'https://aiapoc-aase.streaming.media.azure.net/7705433b-ae8c-4393-84f4-d92d83f2c208/VID_20220130_123824.ism/manifest(format=m3u8-aapl)',
  },
];
